### ISSUE TITLE
Add support for "\t"

### ISSUE THREAD

**Issue by glemiere** [cspotcode/outdent#15]
Sometimes you want indentations in your strings without the indentation from the code :D

**Comment by cspotcode** [comment]
Please create an MCVE on RunKit so I can see exactly what you want to accomplish.

https://npm.runkit.com/outdent

**Comment by cspotcode** [comment]
@glemiere I'm going to close this because it's already supported.  If this does not cover your use-case, please comment and we can re-open the issue.

Example of indented string, with source code indentation removed:
https://runkit.com/embed/rvwjw7kooe7j/clone

From [the README](https://github.com/cspotcode/outdent/):

> You can explicitly specify the indentation level by passing `outdent` as the first interpolated value. Its position sets the indentation level and it is removed from the output:
> 
> ```javascript
> const output = outdent`
>       ${outdent}
>         Yo
>     12345
>           Hello world
> `;
> 
> assert(output === '  Yo\n345\n    Hello world');
> ```
> 
> *Note: `${outdent}` must be alone on its own line without anything before or after it. It cannot be preceded by any non-whitespace characters.*
> *If these conditions are not met, outdent will follow normal indentation-detection behavior.*
