### ISSUE TITLE
Feature Request: Expand array into multiple lines

### ISSUE THREAD

**Issue by yuhr** [cspotcode/outdent#22]
Just as a rough idea, it would be useful if `outdent` can automatically expand this:

```ts
outdent`
  data: ${"foo\nbar".split("\n")}
`
```

To be:

```ts
"data: foo\ndata: bar"
```

Without this feature, I have to do a quite verbose thing, compared to what it does:

```ts
const prefixedMultilineText = "foo\nbar"
  .split("\n")
  .map(s => `data: ${s}`)
  .join("\n")
outdent`
  id: ${Date.now()}
  ${prefixedMultilineText}
`
```

Prefixing entire text is a pretty common pattern for some cases such as logging, and very much similar to indentation.

This feature could be behind an option, but I believe embedding raw arrays is not a common way to interpolate a template, so maybe it's not that surprise to users to change the default behavior (still being a breaking change though). Anyway, I'd love to file a PR if you think this is a reasonable feature.

Thank you for all the great effort to create such a wonderful package!

**Comment by cspotcode** [comment]
Not sure this fits cleanly into outdent; should be a separate function like `prefixLines`.  Outdent is focused on adjusting the _static_ template, leaving interpolated values intentionally untouched.  It tries to behave as if indentation removal were a native feature of the JS language syntax.

We'd need clearer examples showing what's a static string and what's a dynamic runtime value.  The example shows a static `"foo\nbar"` , but I'm guessing in practice, it's a runtime value: you want to prefix every line of some text you read from a file, an input box, an error message, a stack trace.

Also, the example appears to describe a yaml-style key-value syntax, but there are duplicate `data: ` fields. Yes, some formats do use duplicate field names.  But I wonder if a more realistic example is prefixing every line of an Error message with a logging level, something like:

```typescript
console.log(outdent `
    WARN: ${warningMessage}
    Resolve this warning or remove the --fatal-warnings flag.
`)
```

---

You can write a function `prefixLines('WARN: ', multiLineString)` and combine it nicely with `outdent`.

```typescript
outdent`
console.log(outdent `
    ${totalWarnings} warnings encountered:
    ${prefixLines(`WARN: `, warningMessage)}
    Resolve this warning or remove the --fatal-warnings flag.
`)
`
```

I'll close this since I don't think it fits well into outdent and is 3 years old, but anyone feel free to write up some usage examples that clearly and completely describe an intended API.
