### ISSUE TITLE
Request: Expose as function

### ISSUE THREAD

**Issue by Undistraction** [cspotcode/outdent#7]
I was hoping to use outdent within a Jasmine Matcher:

```
 expect(expected).toEqualMultiline(
        `
        Object included invalid value(s)
          – Key '${key1}': Wasn't Array
          – Key '${key2}': Wasn't Boolean`
      )
```

Then within the matcher I was hoping to do:

```
export default (received, expected) => {
  const expectedOutdented = outdent(expected)
  const pass = equals(received, expectedOutdented)
...
```

However it appears that outdent cannot be used as a function.  

```
outdent(expected) // Cannot convert undefined or null to object
        at hasOwnProperty (<anonymous>)
outdent({})(expected) // Returns a function
```

I also tried:
```
outdent`${expected}` // Has no effect on the supplied string.

```

So it would be great if you could expose outdent as a function in the way [dedent](https://www.npmjs.com/package/dedent) does.

FWIW the only workaround is to use outdent in every test:

```
 expect(expected).toEqual(outdent(
        `
        Object included invalid value(s)
          – Key '${key1}': Wasn't Array
          – Key '${key2}': Wasn't Boolean`
      ))
```

**Comment by cspotcode** [comment]
You should invoke your Jasmine matcher as a template tag.

```
expect(expected).toEqualMultiline `
        Object included invalid value(s)
          – Key '${key1}': Wasn't Array
          – Key '${key2}': Wasn't Boolean`
```

Let me know if that does the trick.  EDIT: I just remembered this also requires splatting interpolated values, so your matcher will need a tweak:

```
export default (received, expected, ...interpolatedValues) => {
  const expectedOutdented = outdent(expected, ...interpolatedValues)
  const pass = equals(received, expectedOutdented)
...
```

---

I can offer some insight on why we don't remove indentation from `expected` for the following:

    outdent`${expected}` // Has no effect on the supplied string.

This behavior is by design.  outdent is meant to mimic a static source code transformation, so that it might be implemented as a compile-time transformation in the future.  Removing indentation from the interpolated values is a runtime behavior; outdent intentionally avoids this.  It's also unreliable and confusing if outdent's behavior is affected by the interpolated values rather than being strictly controlled by the template literal as it is seen in the code.

**Comment by Undistraction** [comment]
That works a treat. Thankyou. 

> This behavior is by design

Yes. This makes sense now.

**Comment by KaKi87** [comment]
Hello,

I would like to outdent any code being pasted into a CodeMirror editor.

It would look like this :

```js
this.cmInstance().on('beforeChange', (cm, change) => {
    if(change.origin === 'paste')
        change.update(null, null, outdent(change.text));
});
```

But I need this feature to make it work.

Thanks

**Comment by cspotcode** [comment]
We already have this.  From the readme:

> Outdent can also remove indentation from plain strings via the string method.
